on: [push]

jobs:
  ci:
    name: ci
    runs-on: [self-hosted, macOS, X64]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - name: create conda environment
        run: |
          conda env create --file environment.yml --name test --force
          pip install -e ".[dev]"

      - name: codespell
        run: |
          codespell .

      - name: flake8
        run: |
          flake8 --count setup.py exptorch/ tests/

      - name: black
        run: |
          black --check .

      - name: pytest
        run: |
          pytest tests

      - name: coverage
        run: |
          pytest --cov=exptorch tests
